export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const BUSCAR_TAREA = "BUSCAR_TAREA";
export const MODIFICAR_TAREA = "MODIFICAR_TAREA";
export const BORRAR_TAREA = "BORRAR_TAREA";
export const BORRAR_TODAS_TAREAS = "BORRAR_TODAS_TAREAS";